### ISSUE TITLE
Convert java file to Kotlin data class not generate Stag.Factory

### ISSUE THREAD

**Issue by Ahmed-Abdelmeged** [vimeo/stag-java#168] opened 2018-02-28 17:45 UTC
#### Issue Summary
I have java pojo class after i convert  it to kotlin data class the build fail and Stag factory not generated and it's wired because i have other data classes and it's work fine only this file that cause this bug 

#### Reproduction Steps
Here is the java file
```
@UseStag
public class Article {
    @SerializedName("id")
    private Long id;

    @SerializedName("cell_style")
    private Integer cellStyle;

    @SerializedName("type")
    private String type;

    @SerializedName("ref_id")
    private String refId;

    @SerializedName("url")
    private String url;

    @SerializedName("author")
    private String author;

    @SerializedName("thumbnail")
    private String thumbnail;

    @SerializedName("title")
    private String title;

    @SerializedName("content")
    private List<Content> content = null;

    @SerializedName("comments_count")
    private Integer commentsCount;

    @SerializedName("published_at")
    private String publishedAt;

    @SerializedName("is_ltr")
    private Integer ltr;

    @SerializedName("reports")
    private Integer reports;

    @SerializedName("share_url")
    private String shareUrl;

    @SerializedName("tags")
    private List<NewsTag> newsTags = null;

    @SerializedName("source")
    private ChildSource childSource;

    @SerializedName("reactions")
    private List<Reaction> reactions = null;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getCellStyle() {
        return cellStyle;
    }

    public void setCellStyle(Integer cellStyle) {
        this.cellStyle = cellStyle;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getRefId() {
        return refId;
    }

    void setRefId(String refId) {
        this.refId = refId;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getThumbnail() {
        return thumbnail;
    }

    void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public List<Content> getContent() {
        return content;
    }

    public void setContent(List<Content> content) {
        this.content = content;
    }

    public Integer getCommentsCount() {
        return commentsCount;
    }

    void setCommentsCount(Integer commentsCount) {
        this.commentsCount = commentsCount;
    }

    public String getPublishedAt() {
        return publishedAt;
    }

    void setPublishedAt(String publishedAt) {
        this.publishedAt = publishedAt;
    }

    public Integer getLtr() {
        return ltr;
    }

    public void setLtr(Integer ltr) {
        this.ltr = ltr;
    }

    Integer getReports() {
        return reports;
    }

    void setReports(Integer reports) {
        this.reports = reports;
    }

    public String getShareUrl() {
        return shareUrl;
    }

    void setShareUrl(String shareUrl) {
        this.shareUrl = shareUrl;
    }

    public List<NewsTag> getNewsTags() {
        return newsTags;
    }

    void setNewsTags(List<NewsTag> newsTags) {
        this.newsTags = newsTags;
    }

    public ChildSource getChildSource() {
        return childSource;
    }

    void setChildSource(ChildSource childSource) {
        this.childSource = childSource;
    }

    public List<Reaction> getReactions() {
        return reactions;
    }

    public void setReactions(List<Reaction> reactions) {
        this.reactions = reactions;
    }

}
```
and the same file but in kotlin data class and that's not work
```
@UseStag
data class Article(
        @SerializedName("id")
        var id: Long? = null,

        @SerializedName("cell_style")
        var cellStyle: Int? = null,

        @SerializedName("type")
        var type: String? = null,

        @SerializedName("ref_id")
        var refId: String? = null,

        @SerializedName("url")
        var url: String? = null,

        @SerializedName("author")
        var author: String? = null,

        @SerializedName("thumbnail")
        var thumbnail: String? = null,

        @SerializedName("title")
        var title: String? = null,

        @SerializedName("content")
        var content: List<Content>? = null,

        @SerializedName("comments_count")
        var commentsCount: Int? = null,

        @SerializedName("published_at")
        var publishedAt: String? = null,

        @SerializedName("is_ltr")
        var ltr: Int? = null,

        @SerializedName("reports")
        var reports: Int? = null,

        @SerializedName("share_url")
        var shareUrl: String? = null,

        @SerializedName("tags")
        var newsTags: List<NewsTag>? = null,

        @SerializedName("source")
        var childSource: ChildSource? = null,

        @SerializedName("reactions")
        var reactions: List<Reaction>? = null
)
```
#### Expected Behavior
It should work fine as the rest data classes i have

#### Actual Behavior
The build failed and the factory not generated

**Comment by anthonycr** [comment] 2018-03-02 17:09
Is kapt outputting any stacktrace? If it is, could you re-run your build with the `--stacktrace` flag and post the output here? It would help determine what's going on.

If you create another class and remove all the primitive types so it only contains these fields
```kotlin
@UseStag
data class Article (
        @SerializedName("content")
        var content: List<Content>? = null,

        @SerializedName("tags")
        var newsTags: List<NewsTag>? = null,

        @SerializedName("source")
        var childSource: ChildSource? = null,

        @SerializedName("reactions")
        var reactions: List<Reaction>? = null
)
```
does it still fail to compile? I have a hunch that maybe the problem is being triggered by one of the other classes being included here.

**Comment by Ahmed-Abdelmeged** [comment] 2018-03-04 17:12
Of first of all i don't user kapt. I make class called TestArticle with same fields and it compile successfully as excpeted. i run with  `--stacktrace` and there is the output 

```
error: package com.vimeo.stag.generated does not exist
import com.vimeo.stag.generated.Stag;
                               ^
1 error
2 warnings
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileDebugJavaWithJavac'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see the compiler error output for details.
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:50)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:35)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:98)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:51)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:37)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
	at org.gradle.api.internal.tasks.compile.incremental.IncrementalCompilationFinalizer.execute(IncrementalCompilationFinalizer.java:39)
	at org.gradle.api.internal.tasks.compile.incremental.IncrementalCompilationFinalizer.execute(IncrementalCompilationFinalizer.java:24)
	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:207)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:133)
	at com.android.build.gradle.tasks.factory.AndroidJavaCompile.compile(AndroidJavaCompile.java:125)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	... 29 more

```

**Comment by Ahmed-Abdelmeged** [comment] 2018-03-10 15:56
I Fix my issue i switch to kapt. After switching a lot off errors of my others data classes because it complains it need  no argument constructor so it's need default value for each field in the class so i did that and put the Article class and compile again and every thing work as excepted. Thank you for your help :D @anthonycr . another small questions how to disable  printing w: Note: Found getter
w: Note: Looking for setter in the gradle console.

**Comment by anthonycr** [comment] 2018-03-12 13:57
glad you were able to figure out the problem. It's weird that some code compiles without kapt and some won't. Anyway, it's definitely necessary for kotlin projects.

Regarding logging: There's no way to turn that off, but I will file a bug and move all logging behind a debug flag. 

Going to close this one as fixed 😃

**Closed by anthonycr** 2018-03-12 13:57 UTC

**Comment by anthonycr** [comment] 2018-03-12 16:09
I will also add a Kotlin setup section to the readme so that others don't have to go through the same problem.
