### ISSUE TITLE
Custom TypeAdapterFactory not called when using Stag.Factory

### ISSUE THREAD

**Issue by ursusursus** [vimeo/stag-java#142] opened 2017-10-26 23:34 UTC
Hi,
I have a custom PostParseTypeAdapterFactory , which just calls onParseCompleted method on my objects after parsing is finished, to allow for some post processing of values, etc.

```
public class PostParseTypeAdapterFactory implements TypeAdapterFactory {
    public interface PostProcessable {
        void onParseCompleted();
    }

    @Override public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
        final TypeAdapter<T> delegate = gson.getDelegateAdapter(this, type);
        return new TypeAdapter<T>() {
            public void write(JsonWriter out, T value) throws IOException {
                delegate.write(out, value);
            }

            public T read(JsonReader in) throws IOException {
                T obj = delegate.read(in);
                if (obj instanceof PostProcessable) {
                    ((PostProcessable) obj).onParseCompleted();
                }
                return obj;
            }
        };
    }
}
```

When not using Stag factory, it works as expected, **however with it, the onParseCompleted doesnt get called**

**Comment by anthonycr** [comment] 2017-10-27 13:25
I'll look into this. 

As a work around, if you are able to edit the `PostParseTypeAdapterFactory`, you can initialize it with a `Stag.Factory` instance:
```java
public class PostParseTypeAdapterFactory implements TypeAdapterFactory {

        public interface PostProcessable {

            void onParseCompleted();
        }

        private final TypeAdapterFactory delegateFactory;

        public PostParseTypeAdapterFactory(final TypeAdapterFactory delegate) {
            delegateFactory = delegate;
        }

        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            final TypeAdapter<T> delegate = delegateFactory.create(gson, type);
            return new TypeAdapter<T>() {
                public void write(JsonWriter out, T value) throws IOException {
                    delegate.write(out, value);
                }

                public T read(JsonReader in) throws IOException {
                    T obj = delegate.read(in);
                    if (obj instanceof PostProcessable) {
                        ((PostProcessable) obj).onParseCompleted();
                    }
                    return obj;
                }
            };
        }
    }

// Use as follows
final Gson gson = new GsonBuilder()
                        .registerTypeAdapterFactory(new PostParseTypeAdapterFactory(new Stag.Factory()))
                        .create();
```

**Comment by ursusursus** [comment] 2017-10-27 17:29
Workaround doesnt help, as `public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type)` gets called only for the top level object, not its fields (at least in my case)

**Comment by ursusursus** [comment] 2017-11-12 19:36
any progress on this or where should I look?

**Comment by anthonycr** [comment] 2017-11-14 21:15
@ursusursus sorry for the delayed reply. I played around with this, and was able to get the `PostParseTypeAdapterFactory` to work as expected. By just registering both factories, I am getting the `onParseCompleted` call. 

Here's the code I'm using:

The model:
```java
@UseStag
public class DebugModel implements PostProcessable {

    @SerializedName("hello")
    public String hello;

    @SerializedName("goodbye")
    public String goodbye;

    @Override
    public void onParseCompleted() {
        System.out.println("DEBUG - onParseCompleted: " + hello + " " + goodbye);
    }
}
```
The parsing code:
```java
final Gson gson = new GsonBuilder()
                .registerTypeAdapterFactory(new Stag.Factory())
                .registerTypeAdapterFactory(new PostParseTypeAdapterFactory())
                .create();

final DebugModel debugModel = gson.fromJson("{\"hello\":\"test 1\",\"goodbye\":\"test 2\"}", DebugModel.class);

System.out.println("DEBUG - parsing: " + debugModel.hello + " " + debugModel.goodbye);
```
And the log output I am seeing:
```
11-14 16:04:54.002 16823-16823/? I/System.out: DEBUG - onParseCompleted: test 1 test 2
11-14 16:04:54.002 16823-16823/? I/System.out: DEBUG - parsing: test 2 test 1
```
I need to register both the `Stag.Factory` as well as the `PostParseTypeAdapterFactory`, but other than that I didn't need to change anything about the sample you posted. Also, the registration order of the factories does not matter as I have tried it both ways with the same output.

Does this differ from how you were consuming it? If so, hopefully this fixes things for you, if not, maybe there are some more details that could help me pinpoint what's happening.

**Comment by ursusursus** [comment] 2017-11-14 21:18
Yes its different, try to nest say list of DebugChildModel inside DebugModel, where DebugChildModel implements PostProcessable

**Comment by anthonycr** [comment] 2017-11-14 21:21
I'll give that a try

**Comment by anthonycr** [comment] 2017-11-14 21:51
I'm seeing consistent behavior with an additional model:

Model containing a list of `DebugModel`:
```java
@UseStag
public class AnotherDebugModel {

    @SerializedName("data")
    public List<DebugModel> data;

}
```
JSON being used to parse:
```json
{  
   "data":[  
      {  
         "hello":"test 1",
         "goodbye":"bug 1"
      },
      {  
         "hello":"test 2",
         "goodbye":"bug 2"
      },
      {  
         "hello":"test 3",
         "goodbye":"bug 3"
      },
      {  
         "hello":"test 4",
         "goodbye":"bug 4"
      },
      {  
         "hello":"test 5",
         "goodbye":"bug 5"
      },
      {  
         "hello":"test 6",
         "goodbye":"bug 6"
      }
   ]
}
```
And debug log output:
```
11-14 16:42:37.800 7087-7087/com.vimeo.sample I/System.out: DEBUG - onParseCompleted: test 1 bug 1
11-14 16:42:37.800 7087-7087/com.vimeo.sample I/System.out: DEBUG - onParseCompleted: test 2 bug 2
11-14 16:42:37.800 7087-7087/com.vimeo.sample I/System.out: DEBUG - onParseCompleted: test 3 bug 3
11-14 16:42:37.800 7087-7087/com.vimeo.sample I/System.out: DEBUG - onParseCompleted: test 4 bug 4
11-14 16:42:37.800 7087-7087/com.vimeo.sample I/System.out: DEBUG - onParseCompleted: test 5 bug 5
11-14 16:42:37.800 7087-7087/com.vimeo.sample I/System.out: DEBUG - onParseCompleted: test 6 bug 6
11-14 16:42:37.800 7087-7087/com.vimeo.sample I/System.out: DEBUG - parsing: [com.vimeo.sample.bug.DebugModel@a51b5f18, com.vimeo.sample.bug.DebugModel@a51b63d0, com.vimeo.sample.bug.DebugModel@a51b6680, com.vimeo.sample.bug.DebugModel@a51b6930, com.vimeo.sample.bug.DebugModel@a51b6be0, com.vimeo.sample.bug.DebugModel@a51b6e90]
```

Order of factory registration also does not affect this case. I also see the same behavior if `DebugModel` is explicitly nested inside `AnotherDebugModel` like:
```java
class AnotherDebugModel {
    ...
    class DebugModel {
        ...
    }
}
```

Let me know what I'm missing from your use case.

**Comment by ursusursus** [comment] 2017-11-14 22:16
Ive since refactored to calling the postprocess method manually, but ill look into the vc for you

**Comment by ursusursus** [comment] 2017-11-14 22:34
Ive no idea why is it working for you, here is my setup, naively seems the same as yours

```
@UseStag(UseStag.FieldOption.SERIALIZED_NAME) @NoArgsConstructor(access = AccessLevel.PACKAGE) @Getter
public class CategoryResponse implements PostParseTypeAdapterFactory.PostProcessable {
    @SerializedName("books") List<BookRaw> mBooks;

    @Override public void onParseCompleted() {
        Log.d("Default", "onParseCompleted CategoryResponse");
    }
}

@UseStag(UseStag.FieldOption.SERIALIZED_NAME) @Getter
public class BookRaw implements PostParseTypeAdapterFactory.PostProcessable {
    @SerializedName("id") long mId;
    @SerializedName("title") String mTitle;
    @SerializedName("cover") String mImageUrl;
    @SerializedName("rating") float mRating;
    @SerializedName("authors") String[] mAuthors;
    @SerializedName("type") String mTypeString;

    @Override public void onParseCompleted() {
        Log.d("Default", "onParseComplated BookRaw");
    }
}

@Provides @Singleton Gson gson() {
        return new GsonBuilder()
                .registerTypeAdapterFactory(new Stag.Factory())
                .registerTypeAdapterFactory(new PostParseTypeAdapterFactory())
                .create();
    }
```

JSON
```
{
    "books": [
        {
            "id": 232,
            "type": "book",
            "rating": 0,
            "title": "Adventures of Huckleberry Finn",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id237_size3.jpg",
            "authors": [
                "Mark Twain"
            ]
        },
        {
            "id": 259,
            "type": "book",
            "rating": 0,
            "title": "Adventures of Sherlock Holmes, The",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id264_size3.jpg",
            "authors": [
                "Arthur Conan Doyle"
            ]
        },
        {
            "id": 262,
            "type": "book",
            "rating": 0,
            "title": "Adventures of Tom Sawyer",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id267_size3.jpg",
            "authors": [
                "Mark Twain"
            ]
        },
        {
            "id": 417,
            "type": "book",
            "rating": 0,
            "title": "Alice's Adventures in Wonderland",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id428_size3.jpg",
            "authors": [
                "Lewis Carroll"
            ]
        },
        {
            "id": 4108,
            "type": "book",
            "rating": 0,
            "title": "Count of Monte Cristo, The",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id4185_size3.jpg",
            "authors": [
                "Alexandre Dumas",
                "p\u00e8re"
            ]
        },
        {
            "id": 7808,
            "type": "book",
            "rating": 0,
            "title": "Great Expectations",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id7955_size3.jpg",
            "authors": [
                "Charles Dickens"
            ]
        },
        {
            "id": 10190,
            "type": "book",
            "rating": 0,
            "title": "Jungle Book, The",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id10371_size3.jpg",
            "authors": [
                "Rudyard Kipling"
            ]
        },
        {
            "id": 11411,
            "type": "book",
            "rating": 0,
            "title": "Les Miserables",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id11602_size3.jpg",
            "authors": [
                "Victor Hugo"
            ]
        },
        {
            "id": 13353,
            "type": "book",
            "rating": 0,
            "title": "Metamorphosis",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id13568_size3.jpg",
            "authors": [
                "Franz Kafka"
            ]
        },
        {
            "id": 13612,
            "type": "book",
            "rating": 0,
            "title": "Moby Dick",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id13833_size3.jpg",
            "authors": [
                "Herman Melville"
            ]
        },
        {
            "id": 16014,
            "type": "book",
            "rating": 0,
            "title": "Picture of Dorian Gray, The",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id16267_size3.jpg",
            "authors": [
                "Oscar Wilde"
            ]
        },
        {
            "id": 16546,
            "type": "book",
            "rating": 0,
            "title": "Pride and Prejudice",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id16806_size3.jpg",
            "authors": [
                "Jane Austen"
            ]
        },
        {
            "id": 19790,
            "type": "book",
            "rating": 0,
            "title": "Strange Case of Dr. Jekyll and Mr. Hyde, The",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id20108_size3.jpg",
            "authors": [
                "Robert Louis Stevenson"
            ]
        },
        {
            "id": 21293,
            "type": "book",
            "rating": 0,
            "title": "Ulysses",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id21646_size3.jpg",
            "authors": [
                "James Joyce"
            ]
        },
        {
            "id": 21956,
            "type": "book",
            "rating": 0,
            "title": "War and Peace",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id22321_size3.jpg",
            "authors": [
                "Leo Nikoleyevich Tolstoy"
            ]
        },
        {
            "id": 22846,
            "type": "book",
            "rating": 0,
            "title": "Wuthering Heights",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id23229_size3.jpg",
            "authors": [
                "Emily Bront\u00eb"
            ]
        },
        {
            "id": 21,
            "type": "book",
            "rating": 0,
            "title": "20,000 Leagues Under the Seas (2nd version)",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id23_size3.jpg",
            "authors": [
                "Jules Verne"
            ]
        },
        {
            "id": 281,
            "type": "book",
            "rating": 0,
            "title": "Aesop's Fables",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id287_size3.jpg",
            "authors": [
                "Aesop"
            ]
        },
        {
            "id": 329,
            "type": "book",
            "rating": 0,
            "title": "Age of Innocence, The",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id337_size3.jpg",
            "authors": [
                "Edith Wharton"
            ]
        },
        {
            "id": 331,
            "type": "book",
            "rating": 0,
            "title": "Age of Reason, The",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id339_size3.jpg",
            "authors": [
                "Thomas Paine"
            ]
        },
        {
            "id": 412,
            "type": "book",
            "rating": 0,
            "title": "Alice in Wonderland",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id423_size3.jpg",
            "authors": [
                "Lewis Carroll"
            ]
        },
        {
            "id": 797,
            "type": "book",
            "rating": 0,
            "title": "Analects of Confucius, The",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id818_size3.jpg",
            "authors": [
                "Confucius"
            ]
        },
        {
            "id": 899,
            "type": "book",
            "rating": 0,
            "title": "Anna Karenina",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id920_size3.jpg",
            "authors": [
                "Leo Nikoleyevich Tolstoy"
            ]
        },
        {
            "id": 916,
            "type": "book",
            "rating": 0,
            "title": "Anne of Green Gables",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id937_size3.jpg",
            "authors": [
                "Lucy Maud Montgomery"
            ]
        },
        {
            "id": 999,
            "type": "book",
            "rating": 0,
            "title": "Arabian Nights Entertainments, The",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id1026_size3.jpg",
            "authors": [
                "Anonymous"
            ]
        },
        {
            "id": 1079,
            "type": "book",
            "rating": 0,
            "title": "Around the World in 80 Days",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id1107_size3.jpg",
            "authors": [
                "Jules Verne"
            ]
        },
        {
            "id": 1103,
            "type": "book",
            "rating": 0,
            "title": "Art of Money Getting, The",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id1131_size3.jpg",
            "authors": [
                "P.T. Barnum"
            ]
        },
        {
            "id": 1112,
            "type": "book",
            "rating": 0,
            "title": "Art of War, The",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id1140_size3.jpg",
            "authors": [
                "Sun Tzu"
            ]
        },
        {
            "id": 1412,
            "type": "book",
            "rating": 0,
            "title": "Autobiography of Benjamin Franklin",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id1441_size3.jpg",
            "authors": [
                "Benjamin Franklin"
            ]
        },
        {
            "id": 1694,
            "type": "book",
            "rating": 0,
            "title": "Beautiful and the Damned, The",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id1730_size3.jpg",
            "authors": [
                "F. Scott Fitzgerald"
            ]
        },
        {
            "id": 1809,
            "type": "book",
            "rating": 0,
            "title": "Beowulf",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id1847_size3.jpg",
            "authors": [
                "Anonymous"
            ]
        },
        {
            "id": 1899,
            "type": "book",
            "rating": 0,
            "title": "Bible, The",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id1939_size3.jpg",
            "authors": [
                "Anonymous"
            ]
        },
        {
            "id": 2015,
            "type": "book",
            "rating": 0,
            "title": "Black Beauty",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id2057_size3.jpg",
            "authors": [
                "Anna Sewell"
            ]
        },
        {
            "id": 2559,
            "type": "book",
            "rating": 0,
            "title": "Brothers Karamazov, The",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id2617_size3.jpg",
            "authors": [
                "Fyodor Dostoyevsky"
            ]
        },
        {
            "id": 2783,
            "type": "book",
            "rating": 0,
            "title": "Call of the Wild, The",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id2843_size3.jpg",
            "authors": [
                "Jack London"
            ]
        },
        {
            "id": 2857,
            "type": "book",
            "rating": 0,
            "title": "Candide",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id2917_size3.jpg",
            "authors": [
                "Voltaire"
            ]
        },
        {
            "id": 2870,
            "type": "book",
            "rating": 0,
            "title": "Canterbury Tales and Other Poems",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id2930_size3.jpg",
            "authors": [
                "Geoffrey Chaucer"
            ]
        },
        {
            "id": 3684,
            "type": "book",
            "rating": 0,
            "title": "Collected Works of Poe",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id3755_size3.jpg",
            "authors": [
                "Edgar Allan Poe"
            ]
        },
        {
            "id": 3780,
            "type": "book",
            "rating": 0,
            "title": "Communist Manifesto, The",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id3853_size3.jpg",
            "authors": [
                "Karl Marx"
            ]
        },
        {
            "id": 4200,
            "type": "book",
            "rating": 0,
            "title": "Crime and Punishment ",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id4281_size3.jpg",
            "authors": [
                "Fyodor Dostoyevsky"
            ]
        },
        {
            "id": 4339,
            "type": "book",
            "rating": 0,
            "title": "Curious Case of Benjamin Button, The",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id4420_size3.jpg",
            "authors": [
                "F. Scott Fitzgerald"
            ]
        },
        {
            "id": 5250,
            "type": "book",
            "rating": 0,
            "title": "Divine Comedy: Inferno",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id5345_size3.jpg",
            "authors": [
                "Dante Alighieri"
            ]
        },
        {
            "id": 5426,
            "type": "book",
            "rating": 0,
            "title": "Dracula",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id5528_size3.jpg",
            "authors": [
                "Bram Stoker"
            ]
        },
        {
            "id": 6352,
            "type": "book",
            "rating": 0,
            "title": "Fairy Tales of Hans Christian Andersen",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id6468_size3.jpg",
            "authors": [
                "Hans Christian Andersen"
            ]
        },
        {
            "id": 6408,
            "type": "book",
            "rating": 0,
            "title": "Fanny Hill",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id6524_size3.jpg",
            "authors": [
                "John Cleland"
            ]
        },
        {
            "id": 6423,
            "type": "book",
            "rating": 0,
            "title": "Far From the Madding Crowd",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id6539_size3.jpg",
            "authors": [
                "Thomas Hardy"
            ]
        },
        {
            "id": 6468,
            "type": "book",
            "rating": 0,
            "title": "Faust",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id6584_size3.jpg",
            "authors": [
                "Johann Wolfgang von Goethe"
            ]
        },
        {
            "id": 6716,
            "type": "book",
            "rating": 0,
            "title": "Flatland",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id6836_size3.jpg",
            "authors": [
                "Edwin A. Abbott"
            ]
        },
        {
            "id": 7006,
            "type": "book",
            "rating": 0,
            "title": "Frankenstein",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id7131_size3.jpg",
            "authors": [
                "Mary Wollstonecraft Shelley"
            ]
        },
        {
            "id": 7414,
            "type": "book",
            "rating": 0,
            "title": "Gettysburg Address",
            "cover": "https:\/\/s3.amazonaws.com\/spreadsong-book-covers\/book_id7549_size3.jpg",
            "authors": [
                "Abraham Lincoln"
            ]
        }
    ]
}
```


If I use .registerTypeAdapterFactory(new Stag.Factory()), I only see "onParseCompleted CategoryResponse", If I remove the line, I see "onParseCompleted CategoryResponse", and x "onParseComplated BookRaw")

**Comment by anthonycr** [comment] 2017-11-14 23:12
Okay, this is a really dumb mistake on my part... but the reason I was seeing the "correct" behavior was because the type adapters weren't actually getting generated for me, so registering the type adapter with gson wasn't actually doing anything. After fixing my setup, I am seeing the exact behavior you are seeing. Thanks for being patient.

Contrary to my previous comment, order **does** matter, so I am seeing that if I do
```java
.registerTypeAdapterFactory(new PostParseTypeAdapterFactory())
.registerTypeAdapterFactory(new Stag.Factory())
```
I do not see any calls to `onParseCompleted`, which doesn't make sense until you dig into the Gson code and see that they use the first type adapter they come across, and since registering like such results in a list of `[Stag.Factory, PostParseTypeAdapterFactory]`. If I reverse the order
```java
.registerTypeAdapterFactory(new Stag.Factory())
.registerTypeAdapterFactory(new PostParseTypeAdapterFactory())
```
I see a single call to `onParseCompleted`, exactly as you are reporting.

I believe this is the result of the way stag aggressively caches `TypeAdapters`, I will look for a work-around.

**Comment by anthonycr** [comment] 2017-11-20 14:12
Okay, so right now there is no good work around to this problem. The cause of the problem is that aggressively caches `TypeAdapter`s during compilation, so if you have an adapter for type `A`, which itself has a reference to type `B` which also has an adapter, stag will perform the lookup for type `B` at compilation time, rather than at run time. Since the only adapters it knows about at compile time are stag generated, it will choose stag adapters over run time registered adapters always.

This is a bug, and will be fixed in an upcoming PR https://github.com/vimeo/stag-java/pull/145. Thanks for raising this issue.

**Comment by anthonycr** [comment] 2017-12-18 14:57
Closing as fixed. Fixed in https://github.com/vimeo/stag-java/pull/145 and verified in https://github.com/vimeo/stag-java/pull/148. Next release, coming this week, will have the fix.

**Closed by anthonycr** 2017-12-18 14:57 UTC
Labels: bug
