### ISSUE TITLE
Stag with Kotlin Data Classes

### ISSUE THREAD

**Issue by reastland** [vimeo/stag-java#192] opened 2019-10-01 17:54 UTC
#### Issue Summary
In Kotlin, all data classes are marked as final classes when the app compiles. An error like this is thrown at compile time:

> error: Unable to access field "whatever" in class com.example.stagtest.MyDataModel, field must not be final.

#### Reproduction Steps
```
@UseStag
data class ApiResponse(val dates: List<Day>, val totalGames: Int) {

    @UseStag
    data class Day(
        val totalGames: Int, // 14
        val games: List<Game>
    )
}

Attempt to compile.


```
#### Expected Behavior
App compiles to completion.

#### Actual Behavior
Throws an error:
> /Users/me/StagDeserializationPrototype/app/build/tmp/kapt3/stubs/debug/com/example/stagdeserializationprototype/ApiResponse.java:92: error: Unable to access field "totalGames" in class com.example.stagdeserializationprototype.ApiResponse.Day, field must not be final.
>         private final int totalGames = 0;
>

**Comment by ToxicBakery** [comment] 2019-10-27 16:06
It's not complaining about the field it's complaining about the usage of `val`. Unfortunately, you can not have final values and must use `var`

**Comment by anthonycr** [comment] 2019-10-29 14:00
I would suggest using [`moshi-kotlin-codegen`](https://github.com/square/moshi) with kotlin DTOs. In order to use stag, you must make you make the properties mutable `var` as @ToxicBakery correctly pointed out.

**Comment by anthonycr** [comment] 2019-10-29 14:00
Closing as duplicate of https://github.com/vimeo/stag-java/issues/191

**Closed as completed by anthonycr** 2019-10-29 14:00 UTC
Labels: duplicate, enhancement
